<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions name="CalculationService" targetNamespace="http://cxf.bizruntime.com/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://cxf.bizruntime.com/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <wsdl:types>
    <schema xmlns="http://www.w3.org/2001/XMLSchema">
  <import namespace="http://cxf.bizruntime.com/" schemaLocation="calculation_schema1.xsd"/>
</schema>
  </wsdl:types>
  <wsdl:message name="additionResponse">
    <wsdl:part name="parameters" element="tns:additionResponse">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="addition">
    <wsdl:part name="parameters" element="tns:addition">
    </wsdl:part>
  </wsdl:message>
  <wsdl:portType name="Calculation">
    <wsdl:operation name="addition">
      <wsdl:input name="addition" message="tns:addition">
    </wsdl:input>
      <wsdl:output name="additionResponse" message="tns:additionResponse">
    </wsdl:output>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="CalculationServiceSoapBinding" type="tns:Calculation">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="addition">
      <soap:operation soapAction="" style="document"/>
      <wsdl:input name="addition">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="additionResponse">
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="CalculationService">
    <wsdl:port name="CalculationPort" binding="tns:CalculationServiceSoapBinding">
      <soap:address location="http://localhost:8080/DemoCxf/services/CalculationPort"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>
